// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['app']['App']['AddProfile'](arg1);
}

export function AddRouting(arg1) {
  return window['go']['app']['App']['AddRouting'](arg1);
}

export function AddSubscription(arg1) {
  return window['go']['app']['App']['AddSubscription'](arg1);
}

export function CheckCoreUpdate(arg1) {
  return window['go']['app']['App']['CheckCoreUpdate'](arg1);
}

export function CheckGeoDataUpdate(arg1) {
  return window['go']['app']['App']['CheckGeoDataUpdate'](arg1);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CloseAllConnections() {
  return window['go']['app']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['app']['App']['CloseConnection'](arg1);
}

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function DeleteProfiles(arg1) {
  return window['go']['app']['App']['DeleteProfiles'](arg1);
}

export function DeleteRouting(arg1) {
  return window['go']['app']['App']['DeleteRouting'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['app']['App']['DeleteSubscription'](arg1);
}

export function DownloadCoreUpdate(arg1) {
  return window['go']['app']['App']['DownloadCoreUpdate'](arg1);
}

export function EnsureGeoData(arg1) {
  return window['go']['app']['App']['EnsureGeoData'](arg1);
}

export function ExportShareLink(arg1) {
  return window['go']['app']['App']['ExportShareLink'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetCoreStatus() {
  return window['go']['app']['App']['GetCoreStatus']();
}

export function GetDNSConfig() {
  return window['go']['app']['App']['GetDNSConfig']();
}

export function GetGeoDataInfo(arg1) {
  return window['go']['app']['App']['GetGeoDataInfo'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetProfiles(arg1) {
  return window['go']['app']['App']['GetProfiles'](arg1);
}

export function GetRoutings() {
  return window['go']['app']['App']['GetRoutings']();
}

export function GetStats() {
  return window['go']['app']['App']['GetStats']();
}

export function GetSubscriptions() {
  return window['go']['app']['App']['GetSubscriptions']();
}

export function GetSystemInfo() {
  return window['go']['app']['App']['GetSystemInfo']();
}

export function ImportFromText(arg1) {
  return window['go']['app']['App']['ImportFromText'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['app']['App']['IsAutoStartEnabled']();
}

export function IsCoreInstalled(arg1) {
  return window['go']['app']['App']['IsCoreInstalled'](arg1);
}

export function RequestQuit() {
  return window['go']['app']['App']['RequestQuit']();
}

export function ResetAllStats() {
  return window['go']['app']['App']['ResetAllStats']();
}

export function ResetStats(arg1) {
  return window['go']['app']['App']['ResetStats'](arg1);
}

export function RestartCore() {
  return window['go']['app']['App']['RestartCore']();
}

export function SetActiveProfile(arg1) {
  return window['go']['app']['App']['SetActiveProfile'](arg1);
}

export function SetActiveRouting(arg1) {
  return window['go']['app']['App']['SetActiveRouting'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['app']['App']['SetAutoStart'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['app']['App']['SetProxyMode'](arg1);
}

export function ShouldCloseToTray() {
  return window['go']['app']['App']['ShouldCloseToTray']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartCore() {
  return window['go']['app']['App']['StartCore']();
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopCore() {
  return window['go']['app']['App']['StopCore']();
}

export function SyncAllSubscriptions() {
  return window['go']['app']['App']['SyncAllSubscriptions']();
}

export function SyncSubscription(arg1) {
  return window['go']['app']['App']['SyncSubscription'](arg1);
}

export function TestAllProfiles() {
  return window['go']['app']['App']['TestAllProfiles']();
}

export function TestProfiles(arg1) {
  return window['go']['app']['App']['TestProfiles'](arg1);
}

export function ToggleCore() {
  return window['go']['app']['App']['ToggleCore']();
}

export function UpdateConfig(arg1) {
  return window['go']['app']['App']['UpdateConfig'](arg1);
}

export function UpdateDNSConfig(arg1) {
  return window['go']['app']['App']['UpdateDNSConfig'](arg1);
}

export function UpdateGeoData(arg1) {
  return window['go']['app']['App']['UpdateGeoData'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['app']['App']['UpdateProfile'](arg1);
}

export function UpdateRouting(arg1) {
  return window['go']['app']['App']['UpdateRouting'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['app']['App']['UpdateSubscription'](arg1);
}
