// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';
import {context} from '../models';
import {app} from '../models';

export function AddProfile(arg1:model.ProfileItem):Promise<void>;

export function AddRouting(arg1:model.RoutingItem):Promise<void>;

export function AddSubscription(arg1:model.SubItem):Promise<void>;

export function CheckCoreUpdate(arg1:model.ECoreType):Promise<service.UpdateInfo>;

export function CheckGeoDataUpdate(arg1:model.ECoreType):Promise<boolean>;

export function ClearLogs():Promise<void>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function Context():Promise<context.Context>;

export function DeleteProfiles(arg1:Array<string>):Promise<void>;

export function DeleteRouting(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function DownloadCoreUpdate(arg1:service.UpdateInfo):Promise<void>;

export function EnsureGeoData(arg1:model.ECoreType):Promise<void>;

export function ExportShareLink(arg1:string):Promise<string>;

export function GetConfig():Promise<model.Config>;

export function GetConnections():Promise<service.ConnectionsResponse>;

export function GetCoreStatus():Promise<model.CoreStatus>;

export function GetDNSConfig():Promise<model.DNSItem>;

export function GetGeoDataInfo(arg1:model.ECoreType):Promise<service.GeoDataInfo>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetProfiles(arg1:string):Promise<Array<model.ProfileItem>>;

export function GetRoutings():Promise<Array<model.RoutingItem>>;

export function GetStats():Promise<Array<model.ServerStatItem>>;

export function GetSubscriptions():Promise<Array<model.SubItem>>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function ImportFromText(arg1:string):Promise<number>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsCoreInstalled(arg1:model.ECoreType):Promise<boolean>;

export function RequestQuit():Promise<void>;

export function ResetAllStats():Promise<void>;

export function ResetStats(arg1:string):Promise<void>;

export function RestartCore():Promise<void>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetActiveRouting(arg1:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetProxyMode(arg1:model.EProxyMode):Promise<void>;

export function ShouldCloseToTray():Promise<boolean>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartCore():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopCore():Promise<void>;

export function SyncAllSubscriptions():Promise<Record<string, number>>;

export function SyncSubscription(arg1:string):Promise<number>;

export function TestAllProfiles():Promise<Array<model.SpeedTestResult>>;

export function TestProfiles(arg1:Array<string>):Promise<Array<model.SpeedTestResult>>;

export function ToggleCore():Promise<void>;

export function UpdateConfig(arg1:model.Config):Promise<void>;

export function UpdateDNSConfig(arg1:model.DNSItem):Promise<void>;

export function UpdateGeoData(arg1:model.ECoreType):Promise<void>;

export function UpdateProfile(arg1:model.ProfileItem):Promise<void>;

export function UpdateRouting(arg1:model.RoutingItem):Promise<void>;

export function UpdateSubscription(arg1:model.SubItem):Promise<void>;
